### PR TITLE
1015 fix keyboard

### PR DESCRIPTION
**Pull request by mattmaloof**
Removed hard-coded keypad and added included keypad to appear when text field is tapped.
Added .gitignore file with .DS_Store added to the file to be ignored.

image
image

#JIRA LINK TASK 1015

### CODE REVIEW

**Review by ChopperTheKing — APPROVED** [review]
Good job on the UI

**Review by gisele-prog — APPROVED** [review]
looks good.

**Review by k-code00 — APPROVED** [review]
the keyboard looks clean. can we make it look like the template?

**Review by gisele-prog — APPROVED** [review]
good work adding  .gitignore

**Pull request merged**
